"""Data models for Unfold API."""

from app.models.base import (
    APIErrorDetail,
    APIErrorResponse,
    APIResponse,
    PaginatedResponse,
    PaginationMeta,
    TimestampMixin,
)
from app.models.document import (
    Document,
    DocumentBase,
    DocumentCreate,
    DocumentLicense,
    DocumentSource,
    DocumentStatus,
    DocumentUpdate,
    DocumentValidation,
)
from app.models.graph import (
    GraphNode,
    GraphNodeBase,
    GraphNodeCreate,
    GraphRelation,
    GraphSearchRequest,
    GraphTraversalRequest,
    NodeType,
    RelationType,
)
from app.models.learning import (
    EngagementMetrics,
    ExportFormat,
    ExportRequest,
    Flashcard,
    FlashcardBase,
    FlashcardCreate,
    FlashcardDifficulty,
    FlashcardReview,
    LearningProgress,
    ReflectionSnapshot,
    ReviewQuality,
)
from app.models.user import (
    LoginRequest,
    RefreshTokenRequest,
    Token,
    TokenPayload,
    User,
    UserBase,
    UserCreate,
    UserInDB,
    UserRole,
    UserUpdate,
)

__all__ = [
    # Base
    "APIErrorDetail",
    "APIErrorResponse",
    "APIResponse",
    "PaginatedResponse",
    "PaginationMeta",
    "TimestampMixin",
    # Document
    "Document",
    "DocumentBase",
    "DocumentCreate",
    "DocumentLicense",
    "DocumentSource",
    "DocumentStatus",
    "DocumentUpdate",
    "DocumentValidation",
    # Graph
    "GraphNode",
    "GraphNodeBase",
    "GraphNodeCreate",
    "GraphRelation",
    "GraphSearchRequest",
    "GraphTraversalRequest",
    "NodeType",
    "RelationType",
    # Learning
    "EngagementMetrics",
    "ExportFormat",
    "ExportRequest",
    "Flashcard",
    "FlashcardBase",
    "FlashcardCreate",
    "FlashcardDifficulty",
    "FlashcardReview",
    "LearningProgress",
    "ReflectionSnapshot",
    "ReviewQuality",
    # User
    "LoginRequest",
    "RefreshTokenRequest",
    "Token",
    "TokenPayload",
    "User",
    "UserBase",
    "UserCreate",
    "UserInDB",
    "UserRole",
    "UserUpdate",
]
