"""
Integration tests for the Adaptive Learning system.
Tests flashcards, spaced repetition, engagement tracking, and exports.

Flashcards are generated by the rule-based fallback (the LLM is switched
off below), so card content is deterministic and no network is needed.
"""

import uuid
from datetime import datetime, timedelta, timezone

import pytest
from fastapi.testclient import TestClient
from sqlalchemy import select, text, update

from app.db import get_session_context
from app.db.models.document import DocumentORM
from app.db.models.learning import FlashcardORM
from app.services.learning import get_flashcard_generator
from tests.pdf_utils import DEFAULT_LINES, make_text_pdf

# What the fallback generator makes from tests.pdf_utils.DEFAULT_LINES
EXPECTED_CARDS = [
    ("_____ was a physicist who worked at the University of Paris", "Marie Curie"),
    ("_____ discovered polonium and radium with Pierre Curie", "Marie Curie"),
    ("_____ was studied by Marie Curie and Henri Becquerel", "Radioactivity"),
    ("The _____ of Paris awarded Marie Curie a doctorate in 1903", "University"),
]

EMPTY_STATS = {
    "total_cards": 0,
    "due_now": 0,
    "due_today": 0,
    "average_ef": 0,
    "average_retention": 0,
    "mature_cards": 0,
    "learning_cards": 0,
}


@pytest.fixture(autouse=True)
def offline_generator(monkeypatch):
    """Use the deterministic rule-based generator, never the LLM API."""
    monkeypatch.setattr(get_flashcard_generator(), "api_key", None)


@pytest.fixture
def learning(api_prefix: str) -> str:
    return f"{api_prefix}/learning"


@pytest.fixture
def uploaded_document(client: TestClient, api_prefix: str, auth_headers: dict) -> dict:
    """Like conftest's uploaded_document, but the PDF is unique to the test.

    Each test's document then has its own doc_id however uploads are
    deduplicated. The marker line is too short to become a flashcard, so
    the generated cards are still EXPECTED_CARDS.
    """
    pdf = make_text_pdf([*DEFAULT_LINES, f"Ref {uuid.uuid4().hex[:8]}"])
    response = client.post(
        f"{api_prefix}/documents/upload",
        files={"file": ("curie.pdf", pdf, "application/pdf")},
        headers=auth_headers,
    )
    assert response.status_code == 201, response.text
    return response.json()["document"]


@pytest.fixture
def generated_cards(
    client: TestClient, learning: str, auth_headers: dict, uploaded_document: dict
) -> list[dict]:
    """Generate (and store) flashcards from the auth_headers user's document."""
    response = client.post(
        f"{learning}/flashcards/generate",
        json={"document_id": uploaded_document["doc_id"]},
        headers=auth_headers,
    )
    assert response.status_code == 200, response.text
    return response.json()["flashcards"]


def run_db(client: TestClient, fn, *args):
    """Run ``await fn(session, *args)`` in a fresh DB session on the app's loop."""

    async def runner():
        async with get_session_context() as session:
            return await fn(session, *args)

    return client.portal.call(runner)


async def _card_rows(session, document_id: str) -> list[FlashcardORM]:
    # Fresh statistics make the planner pick a sequential scan, as autovacuum
    # does mid-run; ordering must not depend on the physical row order.
    await session.execute(text("ANALYZE flashcards"))
    result = await session.execute(
        select(FlashcardORM)
        .where(FlashcardORM.document_id == document_id)
        .order_by(FlashcardORM.created_at)
    )
    return list(result.scalars().all())


async def _make_due(session, card_id: str) -> None:
    """Pretend the card's review date has passed (e.g. a day went by)."""
    await session.execute(
        update(FlashcardORM)
        .where(FlashcardORM.card_id == card_id)
        .values(next_review=datetime.now(timezone.utc) - timedelta(minutes=1))
    )


async def _clear_content(session, doc_id: str) -> None:
    await session.execute(
        update(DocumentORM).where(DocumentORM.doc_id == doc_id).values(content="  ")
    )


def _due_ids(client: TestClient, learning: str, headers: dict) -> list[str]:
    response = client.get(f"{learning}/flashcards/due", headers=headers)
    assert response.status_code == 200
    return [card["card_id"] for card in response.json()["due_cards"]]


class TestFlashcardAuth:
    """Every flashcard endpoint needs a bearer token."""

    @pytest.mark.parametrize(
        "method, path, body",
        [
            ("get", "/flashcards", None),
            ("post", "/flashcards", {"document_id": "d", "question": "q", "answer": "a"}),
            ("delete", "/flashcards/card_123", None),
            ("post", "/flashcards/generate", {"document_id": "d"}),
            ("get", "/flashcards/due", None),
            ("get", "/flashcards/upcoming", None),
            ("get", "/flashcards/stats", None),
            ("post", "/flashcards/review", {"card_id": "card_123", "quality": 4}),
        ],
    )
    def test_requires_auth(
        self, client: TestClient, learning: str, method: str, path: str, body
    ):
        kwargs = {"json": body} if body is not None else {}
        response = client.request(method.upper(), f"{learning}{path}", **kwargs)
        assert response.status_code == 401
        assert response.json()["detail"]["code"] == "MISSING_TOKEN"


class TestFlashcardGeneration:
    """POST /learning/flashcards/generate reads the stored document text."""

    def test_generate_from_uploaded_document(
        self, generated_cards: list[dict], uploaded_document: dict
    ):
        assert [(c["question"], c["answer"]) for c in generated_cards] == EXPECTED_CARDS
        ids = [card["card_id"] for card in generated_cards]
        assert len(set(ids)) == len(ids)
        now = datetime.now(timezone.utc)
        for card in generated_cards:
            assert str(uuid.UUID(card["card_id"])) == card["card_id"]
            assert card["document_id"] == uploaded_document["doc_id"]
            assert card["hint"] is None
            assert card["card_type"] == "recall"
            assert card["difficulty"] == "medium"
            assert card["interval_days"] == 0
            assert card["repetitions"] == 0
            assert card["easiness_factor"] == 2.5
            assert datetime.fromisoformat(card["next_review"]) <= now

    def test_generate_response_shape(
        self,
        client: TestClient,
        learning: str,
        auth_headers: dict,
        uploaded_document: dict,
    ):
        response = client.post(
            f"{learning}/flashcards/generate",
            json={"document_id": uploaded_document["doc_id"], "num_cards": 2},
            headers=auth_headers,
        )
        assert response.status_code == 200
        body = response.json()
        assert body["document_id"] == uploaded_document["doc_id"]
        assert body["count"] == 2
        assert body["duplicates_skipped"] == 0
        assert [c["answer"] for c in body["flashcards"]] == ["Marie Curie"] * 2

    def test_generated_cards_are_due_with_content(
        self,
        client: TestClient,
        learning: str,
        auth_headers: dict,
        generated_cards: list[dict],
    ):
        response = client.get(f"{learning}/flashcards/due", headers=auth_headers)
        assert response.status_code == 200
        body = response.json()
        assert body["total_due"] == len(generated_cards)
        assert [c["card_id"] for c in body["due_cards"]] == [
            c["card_id"] for c in generated_cards
        ]
        for due, generated in zip(body["due_cards"], generated_cards):
            assert due["question"] == generated["question"]
            assert due["answer"] == generated["answer"]
            assert due["document_id"] == generated["document_id"]
            assert due["days_overdue"] == 0

    def test_due_limit_and_document_filter(
        self,
        client: TestClient,
        learning: str,
        auth_headers: dict,
        generated_cards: list[dict],
        uploaded_document: dict,
    ):
        response = client.get(
            f"{learning}/flashcards/due", params={"limit": 1}, headers=auth_headers
        )
        assert response.status_code == 200
        assert len(response.json()["due_cards"]) == 1
        assert response.json()["total_due"] == len(generated_cards)

        response = client.get(
            f"{learning}/flashcards/due",
            params={"document_id": "sha256:other"},
            headers=auth_headers,
        )
        assert response.json() == {"due_cards": [], "total_due": 0}

    def test_generate_other_users_document_returns_404(
        self,
        client: TestClient,
        learning: str,
        other_auth_headers: dict,
        uploaded_document: dict,
    ):
        response = client.post(
            f"{learning}/flashcards/generate",
            json={"document_id": uploaded_document["doc_id"]},
            headers=other_auth_headers,
        )
        assert response.status_code == 404
        assert response.json()["detail"]["code"] == "NOT_FOUND"

    def test_generate_unknown_document_returns_404(
        self, client: TestClient, learning: str, auth_headers: dict, mock_document_id: str
    ):
        response = client.post(
            f"{learning}/flashcards/generate",
            json={"document_id": mock_document_id},
            headers=auth_headers,
        )
        assert response.status_code == 404
        assert response.json()["detail"]["code"] == "NOT_FOUND"

    def test_generate_document_without_text_returns_422(
        self,
        client: TestClient,
        learning: str,
        auth_headers: dict,
        uploaded_document: dict,
    ):
        run_db(client, _clear_content, uploaded_document["doc_id"])
        response = client.post(
            f"{learning}/flashcards/generate",
            json={"document_id": uploaded_document["doc_id"]},
            headers=auth_headers,
        )
        assert response.status_code == 422
        assert response.json()["detail"]["code"] == "NO_CONTENT"
        assert client.get(f"{learning}/flashcards", headers=auth_headers).json() == {
            "flashcards": [],
            "total": 0,
        }

    @pytest.mark.parametrize(
        "payload, loc",
        [
            ({}, ["body", "document_id"]),
            ({"document_id": "d", "num_cards": 0}, ["body", "num_cards"]),
            ({"document_id": "d", "num_cards": 51}, ["body", "num_cards"]),
        ],
    )
    def test_generate_validation(
        self, client: TestClient, learning: str, auth_headers: dict, payload, loc
    ):
        response = client.post(
            f"{learning}/flashcards/generate", json=payload, headers=auth_headers
        )
        assert response.status_code == 422
        assert response.json()["detail"][0]["loc"] == loc

    def test_no_transaction_held_during_generation(
        self,
        client: TestClient,
        learning: str,
        auth_headers: dict,
        uploaded_document: dict,
        monkeypatch,
    ):
        """The request's read transaction ends before the generator runs.

        An LLM call can take up to a minute, and PostgreSQL closes
        connections that sit idle in a transaction for 60 s.
        """
        generator = get_flashcard_generator()
        original = generator.generate_flashcards
        idle_in_transaction = []

        async def generate_and_check(**kwargs):
            async with get_session_context() as session:
                result = await session.execute(
                    text(
                        "SELECT count(*) FROM pg_stat_activity "
                        "WHERE datname = current_database() "
                        "AND state LIKE 'idle in transaction%' "
                        "AND pid <> pg_backend_pid()"
                    )
                )
                idle_in_transaction.append(result.scalar())
            return await original(**kwargs)

        monkeypatch.setattr(generator, "generate_flashcards", generate_and_check)
        response = client.post(
            f"{learning}/flashcards/generate",
            json={"document_id": uploaded_document["doc_id"]},
            headers=auth_headers,
        )
        assert response.status_code == 200, response.text
        assert idle_in_transaction == [0]
        assert response.json()["count"] == len(EXPECTED_CARDS)


class TestFlashcardDeduplication:
    """Generating again for a document does not store the same cards twice."""

    def _generate(self, client, learning, headers, doc_id, **extra) -> dict:
        response = client.post(
            f"{learning}/flashcards/generate",
            json={"document_id": doc_id, **extra},
            headers=headers,
        )
        assert response.status_code == 200, response.text
        return response.json()

    def test_regenerate_stores_no_duplicates(
        self,
        client: TestClient,
        learning: str,
        auth_headers: dict,
        generated_cards: list[dict],
        uploaded_document: dict,
    ):
        doc_id = uploaded_document["doc_id"]
        again = self._generate(client, learning, auth_headers, doc_id)
        assert again == {
            "document_id": doc_id,
            "flashcards": [],
            "count": 0,
            "duplicates_skipped": len(EXPECTED_CARDS),
        }
        listing = client.get(
            f"{learning}/flashcards", params={"document_id": doc_id}, headers=auth_headers
        ).json()
        assert listing["total"] == len(EXPECTED_CARDS)
        assert sorted(c["card_id"] for c in listing["flashcards"]) == sorted(
            c["card_id"] for c in generated_cards
        )
        assert sorted(c["question"] for c in listing["flashcards"]) == sorted(
            q for q, _ in EXPECTED_CARDS
        )

    def test_only_new_cards_are_returned(
        self,
        client: TestClient,
        learning: str,
        auth_headers: dict,
        uploaded_document: dict,
    ):
        doc_id = uploaded_document["doc_id"]
        first = self._generate(client, learning, auth_headers, doc_id, num_cards=2)
        assert first["count"] == 2
        assert first["duplicates_skipped"] == 0

        second = self._generate(client, learning, auth_headers, doc_id)
        assert second["count"] == len(EXPECTED_CARDS) - 2
        assert second["duplicates_skipped"] == 2
        assert [c["question"] for c in second["flashcards"]] == [
            q for q, _ in EXPECTED_CARDS[2:]
        ]
        assert len(second["flashcards"]) == second["count"]

        listing = client.get(f"{learning}/flashcards", headers=auth_headers).json()
        assert sorted(c["question"] for c in listing["flashcards"]) == sorted(
            q for q, _ in EXPECTED_CARDS
        )

    def test_manual_card_with_same_question_counts_as_existing(
        self,
        client: TestClient,
        learning: str,
        auth_headers: dict,
        uploaded_document: dict,
    ):
        doc_id = uploaded_document["doc_id"]
        manual = client.post(
            f"{learning}/flashcards",
            json={
                "document_id": doc_id,
                "question": EXPECTED_CARDS[0][0],
                "answer": "Marie Curie",
            },
            headers=auth_headers,
        )
        assert manual.status_code == 201

        body = self._generate(client, learning, auth_headers, doc_id)
        assert body["count"] == len(EXPECTED_CARDS) - 1
        assert body["duplicates_skipped"] == 1
        assert EXPECTED_CARDS[0][0] not in [c["question"] for c in body["flashcards"]]

    def test_same_questions_on_another_document_are_stored(
        self,
        client: TestClient,
        api_prefix: str,
        learning: str,
        auth_headers: dict,
        generated_cards: list[dict],
    ):
        """Duplicates are per user and document."""
        pdf = make_text_pdf([*DEFAULT_LINES, f"Ref {uuid.uuid4().hex[:8]}"])
        upload = client.post(
            f"{api_prefix}/documents/upload",
            files={"file": ("curie2.pdf", pdf, "application/pdf")},
            headers=auth_headers,
        )
        assert upload.status_code == 201
        other_doc = upload.json()["document"]["doc_id"]

        body = self._generate(client, learning, auth_headers, other_doc)
        assert body["count"] == len(EXPECTED_CARDS)
        assert body["duplicates_skipped"] == 0

    def test_duplicates_within_one_generation_are_skipped(
        self,
        client: TestClient,
        learning: str,
        auth_headers: dict,
        uploaded_document: dict,
        monkeypatch,
    ):
        async def repeated(**kwargs):
            card = {"question": "What did Curie discover?", "answer": "Radium"}
            return [dict(card), dict(card), {"question": "Who?", "answer": "Curie"}]

        monkeypatch.setattr(get_flashcard_generator(), "generate_flashcards", repeated)
        body = self._generate(
            client, learning, auth_headers, uploaded_document["doc_id"]
        )
        assert [c["question"] for c in body["flashcards"]] == [
            "What did Curie discover?",
            "Who?",
        ]
        assert body["count"] == 2
        assert body["duplicates_skipped"] == 1


class TestFlashcardReview:
    """POST /learning/flashcards/review applies SM2 to the stored card."""

    def test_review_schedules_card(
        self,
        client: TestClient,
        learning: str,
        auth_headers: dict,
        generated_cards: list[dict],
    ):
        card_id = generated_cards[0]["card_id"]
        before = datetime.now(timezone.utc)
        response = client.post(
            f"{learning}/flashcards/review",
            json={"card_id": card_id, "quality": 4},
            headers=auth_headers,
        )
        assert response.status_code == 200
        body = response.json()
        assert body["card_id"] == card_id
        assert body["quality"] == 4
        assert body["interval_days"] == 1
        assert body["repetitions"] == 1
        assert body["easiness_factor"] == 2.5
        next_review = datetime.fromisoformat(body["next_review"])
        assert before + timedelta(days=1) <= next_review
        assert next_review <= datetime.now(timezone.utc) + timedelta(days=1)

        due = _due_ids(client, learning, auth_headers)
        assert card_id not in due
        assert len(due) == len(generated_cards) - 1

        upcoming = client.get(
            f"{learning}/flashcards/upcoming", params={"days": 2}, headers=auth_headers
        )
        assert upcoming.status_code == 200
        assert upcoming.json()["count"] == 1
        [entry] = upcoming.json()["upcoming_cards"]
        assert entry["card_id"] == card_id
        assert entry["days_until_due"] == 1

    def test_reviewed_card_is_due_again_when_its_date_passes(
        self,
        client: TestClient,
        learning: str,
        auth_headers: dict,
        generated_cards: list[dict],
    ):
        card_id = generated_cards[0]["card_id"]
        client.post(
            f"{learning}/flashcards/review",
            json={"card_id": card_id, "quality": 5},
            headers=auth_headers,
        )
        assert card_id not in _due_ids(client, learning, auth_headers)

        run_db(client, _make_due, card_id)

        due = client.get(f"{learning}/flashcards/due", headers=auth_headers).json()
        [card] = [c for c in due["due_cards"] if c["card_id"] == card_id]
        assert card["repetitions"] == 1
        assert card["interval_days"] == 1
        assert card["easiness_factor"] == 2.6
        assert card["question"] == EXPECTED_CARDS[0][0]

        # The second successful review uses the stored state: interval 6
        second = client.post(
            f"{learning}/flashcards/review",
            json={"card_id": card_id, "quality": 5},
            headers=auth_headers,
        )
        assert second.json()["repetitions"] == 2
        assert second.json()["interval_days"] == 6

    def test_failed_review_resets_card(
        self,
        client: TestClient,
        learning: str,
        auth_headers: dict,
        generated_cards: list[dict],
    ):
        response = client.post(
            f"{learning}/flashcards/review",
            json={"card_id": generated_cards[0]["card_id"], "quality": 1},
            headers=auth_headers,
        )
        assert response.status_code == 200
        assert response.json()["repetitions"] == 0
        assert response.json()["interval_days"] == 1
        assert response.json()["retention_rate"] == 0.0

    def test_repeated_perfect_reviews_cap_the_interval(
        self,
        client: TestClient,
        learning: str,
        auth_headers: dict,
        generated_cards: list[dict],
    ):
        """Back-to-back early reviews compound the interval; the 14th used
        to overflow the next-review date and return 500."""
        card_id = generated_cards[0]["card_id"]
        intervals = []
        for _ in range(16):
            response = client.post(
                f"{learning}/flashcards/review",
                json={"card_id": card_id, "quality": 5},
                headers=auth_headers,
            )
            assert response.status_code == 200, response.text
            intervals.append(response.json()["interval_days"])

        assert intervals[:3] == [1, 6, 17]
        assert intervals == sorted(intervals)
        assert max(intervals) == 36500
        assert intervals[-3:] == [36500, 36500, 36500]
        next_review = datetime.fromisoformat(response.json()["next_review"])
        expected = datetime.now(timezone.utc) + timedelta(days=36500)
        assert abs(next_review - expected) < timedelta(minutes=5)

        stored = client.get(f"{learning}/flashcards", headers=auth_headers).json()
        [card] = [c for c in stored["flashcards"] if c["card_id"] == card_id]
        assert card["interval_days"] == 36500
        assert card["repetitions"] == 16

    def test_review_unknown_card_returns_404(
        self, client: TestClient, learning: str, auth_headers: dict
    ):
        response = client.post(
            f"{learning}/flashcards/review",
            json={"card_id": str(uuid.uuid4()), "quality": 4},
            headers=auth_headers,
        )
        assert response.status_code == 404
        assert response.json()["detail"]["code"] == "NOT_FOUND"
        # Reviewing must never create a card
        listing = client.get(f"{learning}/flashcards", headers=auth_headers)
        assert listing.json()["total"] == 0

    @pytest.mark.parametrize("quality", [10, -1])
    def test_review_invalid_quality(
        self, client: TestClient, learning: str, auth_headers: dict, quality: int
    ):
        response = client.post(
            f"{learning}/flashcards/review",
            json={"card_id": "card_123", "quality": quality},
            headers=auth_headers,
        )
        assert response.status_code == 422
        assert response.json()["detail"][0]["loc"] == ["body", "quality"]


class TestFlashcardIsolation:
    """Cards are private to the user who made them."""

    def test_other_user_cannot_see_or_touch_cards(
        self,
        client: TestClient,
        learning: str,
        auth_headers: dict,
        other_auth_headers: dict,
        generated_cards: list[dict],
    ):
        card_id = generated_cards[0]["card_id"]

        due = client.get(f"{learning}/flashcards/due", headers=other_auth_headers)
        assert due.json() == {"due_cards": [], "total_due": 0}
        stats = client.get(f"{learning}/flashcards/stats", headers=other_auth_headers)
        assert stats.json() == EMPTY_STATS
        listing = client.get(f"{learning}/flashcards", headers=other_auth_headers)
        assert listing.json() == {"flashcards": [], "total": 0}

        review = client.post(
            f"{learning}/flashcards/review",
            json={"card_id": card_id, "quality": 0},
            headers=other_auth_headers,
        )
        assert review.status_code == 404
        delete = client.delete(
            f"{learning}/flashcards/{card_id}", headers=other_auth_headers
        )
        assert delete.status_code == 404

        # The owner's card is untouched
        own = client.get(f"{learning}/flashcards", headers=auth_headers).json()
        [card] = [c for c in own["flashcards"] if c["card_id"] == card_id]
        assert card["repetitions"] == 0
        assert card["interval_days"] == 0
        assert own["total"] == len(generated_cards)


class TestStudyStats:
    """GET /learning/flashcards/stats is computed from the caller's cards."""

    def test_stats_for_new_user(
        self, client: TestClient, learning: str, auth_headers: dict
    ):
        response = client.get(f"{learning}/flashcards/stats", headers=auth_headers)
        assert response.status_code == 200
        assert response.json() == EMPTY_STATS

    def test_stats_reflect_reviews(
        self,
        client: TestClient,
        learning: str,
        auth_headers: dict,
        generated_cards: list[dict],
    ):
        for card, quality in zip(generated_cards[:2], [4, 1]):
            response = client.post(
                f"{learning}/flashcards/review",
                json={"card_id": card["card_id"], "quality": quality},
                headers=auth_headers,
            )
            assert response.status_code == 200

        response = client.get(f"{learning}/flashcards/stats", headers=auth_headers)
        assert response.json() == {
            "total_cards": 4,
            "due_now": 2,
            "due_today": 2,
            "average_ef": 2.5,
            # one card recalled, one forgotten
            "average_retention": 50.0,
            "mature_cards": 0,
            "learning_cards": 4,
        }


class TestFlashcardPersistence:
    """Cards and their schedules live in PostgreSQL, not in process memory."""

    def test_cards_and_reviews_are_stored(
        self,
        client: TestClient,
        api_prefix: str,
        learning: str,
        auth_headers: dict,
        generated_cards: list[dict],
        uploaded_document: dict,
    ):
        user_id = client.get(f"{api_prefix}/auth/me", headers=auth_headers).json()[
            "user_id"
        ]
        client.post(
            f"{learning}/flashcards/review",
            json={"card_id": generated_cards[0]["card_id"], "quality": 4},
            headers=auth_headers,
        )

        rows = run_db(client, _card_rows, uploaded_document["doc_id"])
        assert [row.card_id for row in rows] == [c["card_id"] for c in generated_cards]
        assert [(row.question, row.answer) for row in rows] == EXPECTED_CARDS
        assert {row.user_id for row in rows} == {user_id}
        assert {row.source_node_id for row in rows} == {None}

        reviewed = rows[0]
        assert reviewed.interval == 1
        assert reviewed.repetitions == 1
        assert reviewed.total_reviews == 1
        assert reviewed.correct_reviews == 1
        assert reviewed.last_reviewed is not None
        assert reviewed.next_review > datetime.now(timezone.utc)
        assert all(row.total_reviews == 0 for row in rows[1:])


class TestManualFlashcards:
    """Manual create, list and delete."""

    def test_create_list_delete(
        self,
        client: TestClient,
        learning: str,
        auth_headers: dict,
        uploaded_document: dict,
    ):
        doc_id = uploaded_document["doc_id"]
        response = client.post(
            f"{learning}/flashcards",
            json={
                "document_id": doc_id,
                "question": "What did Marie Curie discover?",
                "answer": "Polonium and radium",
                "hint": "Two elements",
            },
            headers=auth_headers,
        )
        assert response.status_code == 201
        card = response.json()
        assert str(uuid.UUID(card["card_id"])) == card["card_id"]
        assert card["document_id"] == doc_id
        assert card["question"] == "What did Marie Curie discover?"
        assert card["answer"] == "Polonium and radium"
        assert card["hint"] == "Two elements"
        assert card["card_type"] == "manual"
        assert card["difficulty"] == "medium"
        assert card["interval_days"] == 0

        listing = client.get(f"{learning}/flashcards", headers=auth_headers).json()
        assert listing == {"flashcards": [card], "total": 1}
        by_doc = client.get(
            f"{learning}/flashcards",
            params={"document_id": "sha256:other"},
            headers=auth_headers,
        )
        assert by_doc.json() == {"flashcards": [], "total": 0}
        assert _due_ids(client, learning, auth_headers) == [card["card_id"]]

        delete = client.delete(
            f"{learning}/flashcards/{card['card_id']}", headers=auth_headers
        )
        assert delete.status_code == 204
        assert client.get(f"{learning}/flashcards", headers=auth_headers).json() == {
            "flashcards": [],
            "total": 0,
        }
        again = client.delete(
            f"{learning}/flashcards/{card['card_id']}", headers=auth_headers
        )
        assert again.status_code == 404
        assert again.json()["detail"]["code"] == "NOT_FOUND"

    def test_create_for_other_users_document_returns_404(
        self,
        client: TestClient,
        learning: str,
        other_auth_headers: dict,
        uploaded_document: dict,
    ):
        response = client.post(
            f"{learning}/flashcards",
            json={
                "document_id": uploaded_document["doc_id"],
                "question": "q?",
                "answer": "a",
            },
            headers=other_auth_headers,
        )
        assert response.status_code == 404
        assert response.json()["detail"]["code"] == "NOT_FOUND"

    @pytest.mark.parametrize(
        "payload, loc",
        [
            ({"question": "q?", "answer": "a"}, ["body", "document_id"]),
            ({"document_id": "d", "question": "", "answer": "a"}, ["body", "question"]),
            ({"document_id": "d", "question": "q?"}, ["body", "answer"]),
        ],
    )
    def test_create_validation(
        self, client: TestClient, learning: str, auth_headers: dict, payload, loc
    ):
        response = client.post(
            f"{learning}/flashcards", json=payload, headers=auth_headers
        )
        assert response.status_code == 422
        assert response.json()["detail"][0]["loc"] == loc

    def test_deleting_document_deletes_its_cards(
        self,
        client: TestClient,
        api_prefix: str,
        learning: str,
        auth_headers: dict,
        generated_cards: list[dict],
        uploaded_document: dict,
    ):
        response = client.delete(
            f"{api_prefix}/documents/{uploaded_document['doc_id']}",
            headers=auth_headers,
        )
        assert response.status_code == 204
        assert client.get(f"{learning}/flashcards", headers=auth_headers).json() == {
            "flashcards": [],
            "total": 0,
        }


class TestSM2Algorithm:
    """Test the SM2 spaced repetition algorithm."""

    def test_sm2_initial_values(self):
        """Test SM2 algorithm with initial values."""
        from app.services.learning.sm2 import SM2Scheduler, ResponseQuality

        scheduler = SM2Scheduler()
        card_id = "test_card_1"

        scheduler.add_card(card_id)
        state = scheduler.review_card(card_id, ResponseQuality.CORRECT_HESITATION)

        assert state.interval >= 1
        assert state.easiness_factor >= 1.3
        assert state.repetitions == 1

    def test_sm2_quality_5_increases_interval(self):
        """Test that quality 5 increases the interval."""
        from app.services.learning.sm2 import SM2Scheduler, ResponseQuality

        scheduler = SM2Scheduler()
        card_id = "test_card_2"

        scheduler.add_card(card_id)
        state1 = scheduler.review_card(card_id, ResponseQuality.PERFECT)
        interval1 = state1.interval

        state2 = scheduler.review_card(card_id, ResponseQuality.PERFECT)
        interval2 = state2.interval

        assert interval2 >= interval1

    def test_sm2_quality_0_resets(self):
        """Test that quality 0 resets the card."""
        from app.services.learning.sm2 import SM2Scheduler, ResponseQuality

        scheduler = SM2Scheduler()
        card_id = "test_card_3"

        scheduler.add_card(card_id)
        scheduler.review_card(card_id, ResponseQuality.PERFECT)
        scheduler.review_card(card_id, ResponseQuality.PERFECT)

        state = scheduler.review_card(card_id, ResponseQuality.BLACKOUT)

        assert state.interval == 1
        assert state.repetitions == 0

    def test_apply_review_on_stored_state(self):
        """apply_review works on any state, e.g. one loaded from the DB."""
        from app.services.learning.sm2 import (
            CardReviewState,
            ResponseQuality,
            apply_review,
        )

        state = CardReviewState(
            card_id="c", easiness_factor=2.5, interval=6, repetitions=2
        )
        apply_review(state, ResponseQuality.CORRECT_HESITATION)

        assert state.interval == 15  # round(6 * 2.5)
        assert state.repetitions == 3
        assert state.total_reviews == 1
        assert state.correct_reviews == 1

    def test_interval_is_capped(self):
        from app.services.learning.sm2 import (
            MAX_INTERVAL_DAYS,
            CardReviewState,
            ResponseQuality,
            apply_review,
        )

        assert MAX_INTERVAL_DAYS == 36500
        # An interval stored before the cap existed is brought back down.
        state = CardReviewState(
            card_id="c", easiness_factor=2.5, interval=2_900_240, repetitions=13
        )
        apply_review(state, ResponseQuality.PERFECT)
        assert state.interval == 36500
        assert state.next_review - datetime.now(timezone.utc) <= timedelta(days=36500)

        # A failed review still resets the card.
        apply_review(state, ResponseQuality.BLACKOUT)
        assert state.interval == 1
        assert state.repetitions == 0

    def test_days_until_due_rounds_up(self):
        """A card due in 23 hours is due in 1 day, not 0."""
        from app.services.learning.sm2 import CardReviewState

        now = datetime.now(timezone.utc)

        def days(delta: timedelta) -> int:
            return CardReviewState(card_id="c", next_review=now + delta).days_until_due

        assert days(timedelta(hours=23)) == 1
        assert days(timedelta(days=6, hours=1)) == 7
        assert days(timedelta(minutes=-1)) == 0
        assert days(timedelta(hours=-25)) == -1


class TestFallbackGenerator:
    """Rule-based generator used when no LLM is configured."""

    def test_skips_pronoun_and_article_answers(self):
        from app.services.learning.flashcards import FlashcardGenerator

        cards = FlashcardGenerator()._generate_fallback_flashcards(
            "She discovered polonium and radium\nwith Pierre Curie in Paris. "
            "The University of Paris awarded Marie Curie a doctorate in 1903.",
            5,
        )

        assert [(c["question"], c["answer"]) for c in cards] == [
            ("She discovered polonium and radium with _____ in Paris", "Pierre Curie"),
            ("The _____ of Paris awarded Marie Curie a doctorate in 1903", "University"),
        ]

    def test_card_ids_are_unique(self):
        from app.services.learning.flashcards import FlashcardGenerator

        generator = FlashcardGenerator()
        text = "Marie Curie was a physicist who worked at the University of Paris."
        ids = [
            card["card_id"]
            for _ in range(2)
            for card in generator._generate_fallback_flashcards(text, 5)
        ]
        assert len(ids) == 2
        assert len(set(ids)) == 2

    @pytest.mark.parametrize(
        "level, expected",
        [
            ("beginner", "easy"),
            ("intermediate", "medium"),
            ("Advanced", "hard"),
            ("hard", "hard"),
            ("unknown", "medium"),
            (None, "medium"),
        ],
    )
    def test_difficulty_mapping(self, level, expected):
        from app.services.learning.flashcards import to_card_difficulty

        assert to_card_difficulty(level).value == expected


class TestEngagementTracking:
    """Reading sessions are private to the user who started them."""

    def test_start_session_requires_auth(self, client: TestClient, learning: str):
        response = client.post(
            f"{learning}/engagement/session/start", json={"document_id": "doc_123"}
        )
        assert response.status_code == 401

    def test_profile_defaults_use_percent_scale(
        self, client: TestClient, learning: str, auth_headers: dict
    ):
        response = client.get(f"{learning}/engagement/profile", headers=auth_headers)
        assert response.status_code == 200
        body = response.json()
        assert body["documents_read"] == 0
        assert body["avg_scroll_depth"] == 0
        assert body["comprehension_score"] == 50.0

    def test_session_lifecycle(
        self,
        client: TestClient,
        learning: str,
        auth_headers: dict,
        uploaded_document: dict,
    ):
        start = client.post(
            f"{learning}/engagement/session/start",
            json={"document_id": uploaded_document["doc_id"]},
            headers=auth_headers,
        )
        assert start.status_code == 200
        sid = start.json()["session_id"]
        assert sid.startswith("session_")

        for path, payload in [
            ("scroll", {"session_id": sid, "scroll_depth": 0.5}),
            ("dwell-time", {"session_id": sid, "section_id": "s1", "dwell_time_ms": 1500}),
            ("interaction", {"session_id": sid, "interaction_type": "highlight"}),
        ]:
            response = client.post(
                f"{learning}/engagement/{path}", json=payload, headers=auth_headers
            )
            assert response.status_code == 200
            assert response.json() == {"status": "recorded"}

        summary = client.get(
            f"{learning}/engagement/session/{sid}", headers=auth_headers
        ).json()
        assert summary["document_id"] == uploaded_document["doc_id"]
        assert summary["max_scroll_depth_percent"] == 50.0
        assert summary["total_dwell_time_seconds"] == 1.5
        assert summary["highlights_created"] == 1
        assert summary["is_active"] is True

        end = client.post(
            f"{learning}/engagement/session/{sid}/end", headers=auth_headers
        )
        assert end.status_code == 200
        assert end.json()["is_active"] is False

        profile = client.get(
            f"{learning}/engagement/profile", headers=auth_headers
        ).json()
        assert profile["documents_read"] == 1
        assert profile["avg_scroll_depth"] == 50.0
        # 0.5 base - 0.1 (under 2 min) + 0.05 (half read) + 0.04 (one highlight)
        assert profile["comprehension_score"] == 49.0

    def test_other_users_session_returns_404(
        self,
        client: TestClient,
        learning: str,
        auth_headers: dict,
        other_auth_headers: dict,
        uploaded_document: dict,
    ):
        sid = client.post(
            f"{learning}/engagement/session/start",
            json={"document_id": uploaded_document["doc_id"]},
            headers=auth_headers,
        ).json()["session_id"]

        requests = [
            ("GET", f"/engagement/session/{sid}", None),
            ("POST", f"/engagement/session/{sid}/end", None),
            ("POST", "/engagement/scroll", {"session_id": sid, "scroll_depth": 0.9}),
            (
                "POST",
                "/engagement/dwell-time",
                {"session_id": sid, "section_id": "s1", "dwell_time_ms": 10},
            ),
            (
                "POST",
                "/engagement/interaction",
                {"session_id": sid, "interaction_type": "highlight"},
            ),
        ]
        for method, path, body in requests:
            kwargs = {"json": body} if body is not None else {}
            response = client.request(
                method, f"{learning}{path}", headers=other_auth_headers, **kwargs
            )
            assert response.status_code == 404, path
            assert response.json()["detail"] == "Session not found"

        # Nothing the other user sent reached the session
        summary = client.get(
            f"{learning}/engagement/session/{sid}", headers=auth_headers
        ).json()
        assert summary["is_active"] is True
        assert summary["total_interactions"] == 0
        assert summary["max_scroll_depth_percent"] == 0.0

    def test_start_session_on_other_users_document_returns_404(
        self,
        client: TestClient,
        learning: str,
        other_auth_headers: dict,
        uploaded_document: dict,
    ):
        response = client.post(
            f"{learning}/engagement/session/start",
            json={"document_id": uploaded_document["doc_id"]},
            headers=other_auth_headers,
        )
        assert response.status_code == 404
        assert response.json()["detail"]["code"] == "NOT_FOUND"

    def test_nonexistent_session_returns_404(
        self, client: TestClient, learning: str, auth_headers: dict
    ):
        response = client.get(
            f"{learning}/engagement/session/session_nonexistent", headers=auth_headers
        )
        assert response.status_code == 404
        assert response.json()["detail"] == "Session not found"

    def test_invalid_interaction_type(
        self,
        client: TestClient,
        learning: str,
        auth_headers: dict,
        uploaded_document: dict,
    ):
        sid = client.post(
            f"{learning}/engagement/session/start",
            json={"document_id": uploaded_document["doc_id"]},
            headers=auth_headers,
        ).json()["session_id"]
        response = client.post(
            f"{learning}/engagement/interaction",
            json={"session_id": sid, "interaction_type": "bogus"},
            headers=auth_headers,
        )
        assert response.status_code == 400
        assert response.json()["detail"] == "Invalid interaction type"

    def test_recommendations_are_owner_scoped(
        self,
        client: TestClient,
        learning: str,
        auth_headers: dict,
        other_auth_headers: dict,
        uploaded_document: dict,
    ):
        params = {"document_id": uploaded_document["doc_id"]}
        own = client.get(
            f"{learning}/engagement/recommendations", params=params, headers=auth_headers
        )
        assert own.status_code == 200
        assert own.json()["suggested_complexity"] == 50
        other = client.get(
            f"{learning}/engagement/recommendations",
            params=params,
            headers=other_auth_headers,
        )
        assert other.status_code == 404


class TestLearningExport:
    """Export of flashcards supplied by the client."""

    CARDS = [{"question": "What is ATP?", "answer": "Energy currency"}]

    def test_export_requires_auth(self, client: TestClient, learning: str):
        response = client.post(
            f"{learning}/export/flashcards",
            json={"flashcards": self.CARDS, "format": "anki_csv"},
        )
        assert response.status_code == 401

    @pytest.mark.parametrize(
        "fmt, expected",
        [
            ("anki_csv", '"What is ATP?";"Energy currency"'),
            ("obsidian_sr", "What is ATP?"),
            ("json", '"answer": "Energy currency"'),
        ],
    )
    def test_export_formats(
        self, client: TestClient, learning: str, auth_headers: dict, fmt, expected
    ):
        response = client.post(
            f"{learning}/export/flashcards",
            json={"flashcards": self.CARDS, "format": fmt},
            headers=auth_headers,
        )
        assert response.status_code == 200
        body = response.json()
        assert body["format"] == fmt
        assert body["count"] == 1
        assert expected in body["content"]

    def test_export_unsupported_format(
        self, client: TestClient, learning: str, auth_headers: dict
    ):
        response = client.post(
            f"{learning}/export/flashcards",
            json={"flashcards": self.CARDS, "format": "nope"},
            headers=auth_headers,
        )
        assert response.status_code == 400

    @pytest.mark.parametrize("path", ["/export/flashcards", "/export/bundle"])
    def test_export_malformed_card_returns_422(
        self, client: TestClient, learning: str, auth_headers: dict, path: str
    ):
        response = client.post(
            f"{learning}{path}",
            json={"flashcards": [{"question": "q"}], "format": "json"},
            headers=auth_headers,
        )
        assert response.status_code == 422
        assert response.json()["detail"][0]["loc"] == ["body", "flashcards", 0, "answer"]

    def test_export_bundle_zip(
        self, client: TestClient, learning: str, auth_headers: dict
    ):
        response = client.post(
            f"{learning}/export/bundle",
            json={"flashcards": self.CARDS},
            headers=auth_headers,
        )
        assert response.status_code == 200
        assert response.headers["content-type"] == "application/zip"
        assert response.content[:2] == b"PK"


class TestFocusMode:
    """Test focus mode and relevance scoring."""

    def test_focus_order_requires_auth(self, client: TestClient, learning: str):
        response = client.post(
            f"{learning}/relevance/focus-order",
            json={"sections": [{"id": "s1", "content": "x"}], "learning_goal": "physics"},
        )
        assert response.status_code == 401


class TestRankPassages:
    """POST /learning/relevance/rank is bounded and runs off the event loop."""

    def test_ranks_passages(self, client: TestClient, learning: str, auth_headers: dict):
        response = client.post(
            f"{learning}/relevance/rank",
            json={
                "passages": [
                    "Bread rises because yeast produces gas.",
                    "Radioactivity was studied by Marie Curie.",
                ],
                "query": "radioactivity research",
            },
            headers=auth_headers,
        )
        assert response.status_code == 200
        ranked = response.json()["ranked_passages"]
        assert [p["index"] for p in ranked] == [1, 0]

    def test_too_many_passages_returns_422(
        self, client: TestClient, learning: str, auth_headers: dict
    ):
        from app.api.v1.routes.learning import MAX_RANK_PASSAGES

        assert MAX_RANK_PASSAGES == 500
        response = client.post(
            f"{learning}/relevance/rank",
            json={"passages": ["some passage text"] * 501, "query": "passage"},
            headers=auth_headers,
        )
        assert response.status_code == 422
        assert response.json()["detail"][0]["loc"] == ["body", "passages"]

    def test_max_passages_accepted(
        self, client: TestClient, learning: str, auth_headers: dict
    ):
        response = client.post(
            f"{learning}/relevance/rank",
            json={
                "passages": ["some passage text"] * 500,
                "query": "passage",
                "top_k": 3,
            },
            headers=auth_headers,
        )
        assert response.status_code == 200
        assert len(response.json()["ranked_passages"]) == 3

    def test_scoring_runs_in_a_worker_thread(
        self, client: TestClient, learning: str, auth_headers: dict, monkeypatch
    ):
        import asyncio

        from app.services.learning import get_relevance_scorer

        scorer = get_relevance_scorer()
        original = scorer.rank_passages
        on_event_loop = []

        def rank_and_check(**kwargs):
            try:
                asyncio.get_running_loop()
                on_event_loop.append(True)
            except RuntimeError:
                on_event_loop.append(False)
            return original(**kwargs)

        monkeypatch.setattr(scorer, "rank_passages", rank_and_check)
        response = client.post(
            f"{learning}/relevance/rank",
            json={"passages": ["first passage", "second passage"], "query": "passage"},
            headers=auth_headers,
        )
        assert response.status_code == 200
        assert on_event_loop == [False]
