"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-06 20:13:09.633457+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('orcid_id', sa.String(length=50), nullable=True),
    sa.Column('role', sa.Enum('USER', 'EDUCATOR', 'RESEARCHER', 'ADMIN', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('orcid_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('documents',
    sa.Column('doc_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('authors', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('doi', sa.String(length=100), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('license', sa.Enum('CC_BY_4', 'CC_BY_SA_4', 'CC_BY_NC_4', 'CC0', 'MIT', 'UNKNOWN', 'PROPRIETARY', name='document_license'), nullable=True),
    sa.Column('source', sa.Enum('UPLOAD', 'ARXIV', 'PUBMED', 'DOI', 'URL', name='document_source'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'VALIDATED', 'INDEXED', 'FAILED', name='document_status'), nullable=False),
    sa.Column('vector_id', sa.String(length=100), nullable=True),
    sa.Column('graph_nodes', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('doc_id')
    )
    op.create_index(op.f('ix_documents_doi'), 'documents', ['doi'], unique=False)
    op.create_index(op.f('ix_documents_owner_id'), 'documents', ['owner_id'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_table('document_validations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doc_id', sa.String(length=100), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('doi_verified', sa.Boolean(), nullable=False),
    sa.Column('license_verified', sa.Boolean(), nullable=False),
    sa.Column('author_verified', sa.Boolean(), nullable=False),
    sa.Column('provenance_hash', sa.String(length=100), nullable=True),
    sa.Column('validation_errors', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['documents.doc_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doc_id')
    )
    op.create_table('engagement_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=100), nullable=False),
    sa.Column('dwell_time_seconds', sa.Integer(), nullable=False),
    sa.Column('scroll_depth', sa.Float(), nullable=False),
    sa.Column('scroll_velocity', sa.Float(), nullable=False),
    sa.Column('annotations_count', sa.Integer(), nullable=False),
    sa.Column('highlights_count', sa.Integer(), nullable=False),
    sa.Column('chat_queries_count', sa.Integer(), nullable=False),
    sa.Column('last_accessed', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.doc_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_engagement_metrics_document_id'), 'engagement_metrics', ['document_id'], unique=False)
    op.create_index(op.f('ix_engagement_metrics_user_id'), 'engagement_metrics', ['user_id'], unique=False)
    op.create_table('flashcards',
    sa.Column('card_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=100), nullable=False),
    sa.Column('source_node_id', sa.String(length=100), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('hint', sa.Text(), nullable=True),
    sa.Column('card_type', sa.String(length=32), nullable=False),
    sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', name='flashcard_difficulty'), nullable=False),
    sa.Column('easiness', sa.Float(), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.Column('repetitions', sa.Integer(), nullable=False),
    sa.Column('total_reviews', sa.Integer(), nullable=False),
    sa.Column('correct_reviews', sa.Integer(), nullable=False),
    sa.Column('next_review', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_reviewed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.doc_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('card_id')
    )
    op.create_index(op.f('ix_flashcards_document_id'), 'flashcards', ['document_id'], unique=False)
    op.create_index(op.f('ix_flashcards_user_id'), 'flashcards', ['user_id'], unique=False)
    op.create_table('reflection_snapshots',
    sa.Column('snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=100), nullable=True),
    sa.Column('nodes_added', sa.Integer(), nullable=False),
    sa.Column('nodes_deleted', sa.Integer(), nullable=False),
    sa.Column('connections_made', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('insights', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.doc_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('snapshot_id')
    )
    op.create_index(op.f('ix_reflection_snapshots_document_id'), 'reflection_snapshots', ['document_id'], unique=False)
    op.create_index(op.f('ix_reflection_snapshots_user_id'), 'reflection_snapshots', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reflection_snapshots_user_id'), table_name='reflection_snapshots')
    op.drop_index(op.f('ix_reflection_snapshots_document_id'), table_name='reflection_snapshots')
    op.drop_table('reflection_snapshots')
    op.drop_index(op.f('ix_flashcards_user_id'), table_name='flashcards')
    op.drop_index(op.f('ix_flashcards_document_id'), table_name='flashcards')
    op.drop_table('flashcards')
    op.drop_index(op.f('ix_engagement_metrics_user_id'), table_name='engagement_metrics')
    op.drop_index(op.f('ix_engagement_metrics_document_id'), table_name='engagement_metrics')
    op.drop_table('engagement_metrics')
    op.drop_table('document_validations')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_owner_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_doi'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###

    # drop_table doesn't remove PostgreSQL enum types; without this a
    # downgrade followed by an upgrade fails with "type already exists".
    bind = op.get_bind()
    for enum_name in (
        "flashcard_difficulty",
        "document_status",
        "document_source",
        "document_license",
        "user_role",
    ):
        sa.Enum(name=enum_name).drop(bind, checkfirst=True)
